[package]
name = "labcat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
thiserror = "1.0.38"
enum_dispatch= "0.3.11"
rand = "0.8.5"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
ndarray-rand = "0.14.0"
oxidized_l_bfgs_b_c = { path = "oxidized_L_BFGS_B_C" }
statrs = "0.16.0"
egobox-doe = "0.11.0"
sobol = "1.0.2"
pyo3 = { version="^0.15.0", optional=true }
numpy = { version="^0.15.0", optional=true }

[dev-dependencies] 
ndarray = { version = "0.15.6", features = ["rayon", "matrixmultiply-threading", "blas"] }

[target.'cfg(windows)'.dev-dependencies]
ndarray-linalg = { version = "0.16", features = ["intel-mkl-static"] }

[target.'cfg(unix)'.dev-dependencies]
ndarray-linalg = { version = "0.16", features = ["openblas-static"] }


[lib]
name = "algpa_lib"
path = "./src/lib.rs"

[[example]]
name = "gp"

[profile.release]
lto = true

[features]
default = ["f64", "LHS", "PCA"]
f64 = [] # TODO: GET F32 WORKING
python = ["dep:pyo3", "dep:numpy"]
LHS = []
PCA = []